### ISSUE TITLE
hamster-bridge compatibility

### ISSUE THREAD

**Issue by Kudlaty01** [gsobczyk/hamster#27]
I have been trying your fork of hamster and I have realized that it didn't notify my running hamster-bridge instance. I am using hamster-bridge 0.7.0 and only with this version I am unable to upload my worklogs to JIRA. I would like to ask if I am missing anything or should I change the hamster-bridge version?
I am also experiencing a system crash when opening the _last activities_ tray menu position. I am using Debian Jessie with i3 windows manager, but for that I don't know if I should send this in another issue.

**Comment by gsobczyk** [comment]
Hej. 

Ta wersja hamstera pozwala na raportowanie w jira bez konieczności instalacji hamster-bridge. To samo dotyczy podpowiadania issue. w/w hamster podpowiada taski po wpisaniu loginu assignee, nazwy projektu lub fragmentu summary. 
Sam nie używam i3, więc niewiele pomogę.
Czy próbowałeś na Unity lub Xfce?

---

Hi.
This version of hamster allows you to upload your worklogs to jira directly (without hamster-bridge). It  also suggests tasks based on jira assignee, project and summary's fragemnt.
I don't use i3, so I couldn't help you with it.

Have you tried it on Unity or Xfce?

**Comment by Kudlaty01** [comment]
Hej @gsobczyk ,
z menedżerów okienek mam tylko Gnome3, Wayland i i3.
Przed chwilą zainstalowałem i na gnomie w menu kontekstowym ostatnie czynności są nierozwijalne, więc też nie ma ryzyka awarii.
> /usr/lib/python2.7/dist-packages/hamster/tray.py:258: Warning: /build/glib2.0-ETetDu/glib2.0-2.48.0/./gobject/gsignal.c:2517: signal 'child-added' is invalid for instance '0x2342a80' of type 'GtkMenu'

Po wejściu w widok `Przegląd` jest widoczny przycisk `Raportuj wybrane`, jednak zaznaczone (wybrane) mogę mieć tylko jedno zadanie i okienko, które się otwiera jest całe białe. W konsoli mam komunikat 

> INFO:external:user: `p********a`, pass: *****
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): mccomprojects.atlassian.net

I potem już nic więcej się nie dzieje


========================================================================
Hey @gsobczyk ,
among windows managers I have only Gnome3, Wayland i i3.
A moment ago I have installed and tested on Gnome3 and in the context menuy the `last activities` is not expandable, to there is no risk of a crash.
> /usr/lib/python2.7/dist-packages/hamster/tray.py:258: Warning: /build/glib2.0-ETetDu/glib2.0-2.48.0/./gobject/gsignal.c:2517: signal 'child-added' is invalid for instance '0x2342a80' of type 'GtkMenu'

After entering the view 'Report' and choosing `Report selected`, but only one task can be selected at time and the window being opened is blank white. Console running is returning the following output:
> INFO:external:user: `p********a`, pass: *****
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): mccomprojects.atlassian.net

and nothing happens next.

**Comment by gsobczyk** [comment]
Whetever it will be fixed with #33 and #32 ?

**Comment by Kudlaty01** [comment]
Nope.
Unfortunately.
Tried to reduce the report day numbers, but currently I'm too scared to try if it would freeze my system (important work on progress)

**Comment by gsobczyk** [comment]
closed because of inactivity
