### ISSUE TITLE
Jira Cloud disabled Basic Auth

### ISSUE THREAD

**Issue by Kudlaty01** [gsobczyk/hamster#32]
Hi,
I'd like to ask if you have considered implementation of oauth or cookie-based auth to jira communication plugin, as for today communication with JIRA is dead

**Comment by gsobczyk** [comment]
I haven't considered it. I'm using Jira Server. I'll merge #33 after correction.

**Comment by Kudlaty01** [comment]
Lucky you are. Company I work in doesn't consider moving to server for a long time. Trying to figure out any to convince them

**Comment by gsobczyk** [comment]
closed because of inactivity
